services:
  backend:
    container_name: backend
    build: backend
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src:/app
    networks:
      - default
  
  cron:
    container_name: cron
    build: cron
    env_file:
      - .env
    volumes:
      - ./cron/src:/app
    networks:
      - default

  frontend:
    container_name: frontend
    build: frontend
    ports:
      - "8081:3000"
    networks:
      - default
  

  mongodb:
    container_name: mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongodb_data:/data/db
    networks:
      - default

networks:
  default:

volumes:
  mongodb_data:
