services:
  backend:
    build: backend
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src:/app
    networks:
      - default
  
  cron:
    build: cron
    env_file:
      - .env
    ports:
      - "8081:8080"
    volumes:
      - ./cron/src:/app
    networks:
      - default

  frontend:
    build: frontend
    networks:
      - default

networks:
  default:
