services:
  backend:
    container_name: backend
    build: backend
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src:/app
    networks:
      - default
  
  cron:
    container_name: cron
    build: cron
    env_file:
      - .env
    volumes:
      - ./cron/src:/app
    networks:
      - default

  frontend:
    container_name: frontend
    build: frontend
    ports:
      - "8081:3000"
    networks:
      - default

networks:
  default:
