import React, { JSX, ChangeEvent, DragEvent, useRef, useState } from "react";

interface PhotoUploadProps {
  selectedFile: File | null;
  onFileChange: (file: File | null) => void;
  onAnalyze: () => void;
  loading: boolean;
  error: string | null;
}

export default function PhotoUpload({
  selectedFile,
  onFileChange,
  onAnalyze,
  loading,
  error,
}: PhotoUploadProps): JSX.Element {
  const fileInputRef = useRef<HTMLInputElement | null>(null);
  const [isDragActive, setIsDragActive] = useState(false);

  const handleFileInputChange = (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0] ?? null;
    onFileChange(file);
  };

  const handleChooseFileClick = () => {
    fileInputRef.current?.click();
  };

  const handleDragOver = (event: DragEvent<HTMLDivElement>) => {
    event.preventDefault();
    event.stopPropagation();
    if (!isDragActive) {
      setIsDragActive(true);
    }
  };

  const handleDragLeave = (event: DragEvent<HTMLDivElement>) => {
    event.preventDefault();
    event.stopPropagation();
    setIsDragActive(false);
  };

  const handleDrop = (event: DragEvent<HTMLDivElement>) => {
    event.preventDefault();
    event.stopPropagation();
    setIsDragActive(false);

    const file = event.dataTransfer.files && event.dataTransfer.files[0];
    if (!file) {
      return;
    }

    if (!file.type.startsWith("image/")) {
      return;
    }

    onFileChange(file);
  };

  const previewUrl = selectedFile ? URL.createObjectURL(selectedFile) : null;

  return (
    <section className="text-analyzer text-analyzer-input">
      <header className="text-analyzer-header">
        <h1 className="text-analyzer-title">Analyze Photo</h1>
        <p className="text-analyzer-subtitle">
          Upload an image to check if it was generated by AI or captured from the real world.
        </p>
      </header>

      <div className="text-analyzer-field">
        <label className="text-analyzer-label" htmlFor="image-input">
          Image to analyze
        </label>
        <div
          className={`photo-upload-dropzone ${isDragActive ? "photo-upload-dropzone--active" : ""}`}
          onDragOver={handleDragOver}
          onDragLeave={handleDragLeave}
          onDrop={handleDrop}
          onClick={handleChooseFileClick}
        >
          <p className="photo-upload-dropzone-text">Drag or upload photo</p>
          <input
            id="image-input"
            ref={fileInputRef}
            type="file"
            accept="image/*"
            className="photo-upload-input-hidden"
            onChange={handleFileInputChange}
            disabled={loading}
          />
        </div>
        {selectedFile && previewUrl && (
          <div className="photo-upload-selected">
            <div className="photo-upload-selected-thumb">
              <img
                src={previewUrl}
                alt={selectedFile.name}
              />
            </div>
            <div className="photo-upload-selected-meta">
              <span className="photo-upload-selected-label">Selected:</span>
              <span className="photo-upload-selected-name">{selectedFile.name}</span>
            </div>
          </div>
        )}
      </div>

      {error && <div className="text-analyzer-error">Error: {error}</div>}

      <div className="text-analyzer-actions">
        <button
          type="button"
          className="text-analyzer-submit"
          onClick={onAnalyze}
          disabled={loading}
        >
          {loading ? "Analyzing..." : "Analyze Image"}
        </button>
      </div>
    </section>
  );
}
