import React, { JSX, ChangeEvent, useRef } from "react";

interface PhotoUploadProps {
  selectedFile: File | null;
  onFileChange: (file: File | null) => void;
  onAnalyze: () => void;
  loading: boolean;
  error: string | null;
}

export default function PhotoUpload({
  selectedFile,
  onFileChange,
  onAnalyze,
  loading,
  error,
}: PhotoUploadProps): JSX.Element {
  const fileInputRef = useRef<HTMLInputElement | null>(null);

  const handleFileInputChange = (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0] ?? null;
    onFileChange(file);
  };

  const handleChooseFileClick = () => {
    fileInputRef.current?.click();
  };

  const previewUrl = selectedFile ? URL.createObjectURL(selectedFile) : null;

  return (
    <section className="text-analyzer text-analyzer-input">
      <header className="text-analyzer-header">
        <h1 className="text-analyzer-title">Analyze Photo</h1>
        <p className="text-analyzer-subtitle">
          Upload an image to check if it was generated by AI or captured from the real world.
        </p>
      </header>

      <div className="text-analyzer-field">
        <label className="text-analyzer-label" htmlFor="image-input">
          Image to analyze
        </label>
        <div className="photo-upload-row">
          <button
            type="button"
            className="photo-upload-button"
            onClick={handleChooseFileClick}
            disabled={loading}
          >
            {/* <span className="photo-upload-icon" aria-hidden="true">
              <svg
                width="18"
                height="18"
                viewBox="0 0 24 24"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  d="M16.5 6.75L9 14.25C8.31 14.94 7.19 14.94 6.5 14.25C5.81 13.56 5.81 12.44 6.5 11.75L13 5.25"
                  stroke="currentColor"
                  strokeWidth="1.6"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                />
                <path
                  d="M11 18.75L14.25 18.75C17.1495 18.75 19.5 16.3995 19.5 13.5C19.5 10.6005 17.1495 8.25 14.25 8.25L7.5 8.25C4.60051 8.25 2.25 10.6005 2.25 13.5C2.25 16.3995 4.60051 18.75 7.5 18.75"
                  stroke="currentColor"
                  strokeWidth="1.6"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                />
              </svg>
            </span> */}
            <span>Choose image</span>
          </button>
          <span className="photo-upload-filename">
            {selectedFile ? selectedFile.name : "No file chosen"}
          </span>
          <input
            id="image-input"
            ref={fileInputRef}
            type="file"
            accept="image/*"
            className="photo-upload-input-hidden"
            onChange={handleFileInputChange}
            disabled={loading}
          />
        </div>
      </div>

      {previewUrl && (
        <div className="text-analyzer-field" aria-label="Image preview">
          <p className="text-analyzer-label">Preview</p>
          <div
            style={{
              borderRadius: 16,
              overflow: "hidden",
              border: "1px solid rgba(148, 163, 184, 0.4)",
              maxHeight: 320,
            }}
          >
            <img
              src={previewUrl}
              alt={selectedFile?.name || "Selected image"}
              style={{ width: "100%", height: "100%", objectFit: "cover" }}
            />
          </div>
        </div>
      )}

      {error && <div className="text-analyzer-error">Error: {error}</div>}

      <div className="text-analyzer-actions">
        <button
          type="button"
          className="text-analyzer-submit"
          onClick={onAnalyze}
          disabled={loading}
        >
          {loading ? "Analyzing..." : "Analyze Image"}
        </button>
      </div>
    </section>
  );
}
