import React from "react";

const options = [
    {
        id: 1,
        label: "AI content",
        description: "Detect how likely the text was generated by AI models.",
    },
    {
        id: 2,
        label: "Manipulation",
        description: "Spot persuasive or emotionally charged wording patterns.",
    },
    {
        id: 3,
        label: "Fact checking",
        description: "Cross-check statements against trusted knowledge sources.",
    },
    {
        id: 4,
        label: "Find source",
        description: "Locate the original publication or author of the text.",
    },
];

export default function TextAnalyzerOptions(): JSX.Element {
    const handleClick = (id: number) => {
        // TODO: hook up analyzer option action
        console.debug("Selected option", id);
    };

    return (
        <div className="text-analyzer-options">
            {options.map((option) => (
                <div key={option.id} className="text-analyzer-option">
                    <button
                        type="button"
                        className="text-analyzer-option-button"
                        onClick={() => handleClick(option.id)}
                    >
                        {option.label}
                    </button>
                    <p className="text-analyzer-option-description">{option.description}</p>
                </div>
            ))}
        </div>
    );
}

