import React, { JSX } from "react";

const options = [
    {
        id: 1,
        label: "AI content",
        description: "Detect how likely the text was generated by AI models.",
    },
    {
        id: 2,
        label: "Manipulation",
        description: "Spot persuasive or emotionally charged wording patterns.",
    },

    {
        id: 3,
        label: "Find source",
        description: "Locate the original publication or author of the text.",
    },
];

interface TextAnalyzerOptionsProps {
    activeId: number | null;
    onSelect: (id: number) => void;
}

export default function TextAnalyzerOptions({ activeId, onSelect }: TextAnalyzerOptionsProps): JSX.Element {

    return (
        <div className="text-analyzer-options">
            {options.map((option) => (
                <div key={option.id} className="text-analyzer-option">
                    <button
                        type="button"
                        className={`text-analyzer-option-button${activeId === option.id ? " text-analyzer-option-button--active" : ""}`}
                        onClick={() => onSelect(option.id)}
                    >
                        {option.label}
                    </button>
                    <p className="text-analyzer-option-description">{option.description}</p>
                </div>
            ))}
        </div>
    );
}
